### ISSUE TITLE
Problem installing recast

### ISSUE THREAD

**Issue by akrasuski** [arl/go-detour#27]
go get -u github.com/arl/go-detour/cmd/recast
# github.com/arl/math32
go/src/github.com/arl/math32/fma.go:8:17: undefined: math.FMA

Ubuntu 18.04.4 LTS

**Comment by arl** [comment]
There was a problem in dependencies, sorry for that.
It should work now.
Let me know

**Comment by akrasuski** [comment]
It seems that I still have some problems: 


go get -v -u github.com/arl/go-detour/cmd/recast
github.com/arl/go-detour (download)
github.com/arl/assertgo (download)
github.com/arl/gogeo (download)
github.com/arl/math32 (download)
github.com/arl/gobj (download)
github.com/spf13/cobra (download)
github.com/spf13/pflag (download)
Fetching https://gopkg.in/yaml.v2?go-get=1
Parsing meta tags from https://gopkg.in/yaml.v2?go-get=1 (status code 200)
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at https://gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
github.com/arl/math32
# github.com/arl/math32
go/src/github.com/arl/math32/fma.go:8:17: undefined: math.FMA

**Comment by arl** [comment]
uhm I guess you're either using a too old version (go 1.14 is now required) or you're using Go in GOPATH mode and not in modules mode.
I believe that updating to the latest go version will solve this
please let me know if it doesn't

**Comment by akrasuski** [comment]
Yes, it was the problem with go version. go 1.14 works. Thank you very much.
